### ISSUE TITLE
sovereignty/structures/ ADM value's decimal 

### ISSUE THREAD

**Issue by Risingson** [ccpgames/esi-issues#353]
example values:
"vulnerability_occupancy_level": 1.7999999999999998
"vulnerability_occupancy_level": 5.1000000000000005

**Comment by a-tal** [comment]
from the spec, vulnerability_occupancy_level is:

```yaml
vulnerability_occupancy_level:
  type: number
  format: float
```

not sure what the issue is here... you'd like us to round this before sending?
