### ISSUE TITLE
Missing corporation contact labels endpoint

### ISSUE THREAD

**Issue by dextermb** [ccpgames/esi-issues#779]
# Feature request

I would like to be able to return labels, on contacts, for a corporation. (There also does not seem to be `POST`, `PUT`, `DELETE` methods for corporation contacts)

### Route

The route should follow the same pattern as the character endpoint (`/characters/{character_id}/contacts/labels`):

```
/corporations/{corporation_id}/contacts/labels
```

### Authentication

Not sure what authentication characters use for labels but seems reasonable:

```
esi-corporations.read_contacts.v1
```

### Use case

This endpoint would be used to return labels that are assigned to a contact, of a corporation, to be displayed in one way or another.

### Example returns

It should be returned in the same format as the character contact labels endpoint.

```

[
    {
        label_id: int,
        label_name: string
    }
]

```

**Comment by CarbonAlabel** [comment]
This should be part of parity work, as the XML API endpoint [/char/ContactList.xml.aspx](https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_contactlist.html) provides a list of corporation, as well as alliance contact labels.

Closely related to this are issues #173 (regarding write access to contact labels) and #174 (a bug/inconsistency with the return format of a contact's labels).

**Comment by warlof** [comment]
up

actually corporation contacts are not sortable due to the lack of this endpoint :(

**Comment by warlof** [comment]
any ETA about that missing endpoint creation ?

**Comment by ccp-zoetrope** [comment]
I'm starting to look into this today so I'll let you know once I've dug in a bit.

**Comment by ccp-zoetrope** [comment]
I'm sorry to say I found a bug in the deployed code for this in the monolith and have fixed it, but that means it will not be available until next week :(

**Comment by ccp-zoetrope** [comment]
Sure, there will be two new endpoints, `/v1/corporations/{corporation_id}/contacts/labels/` and `/v1/alliances/{alliance_id}/contacts/labels/` which literally have the same structure as [/v1/characters/{character_id}/contacts/labels/](https://esi.tech.ccp.is/ui/#/Contacts/get_characters_character_id_contacts_labels). 

The other change happening for this whole thing will be the addition of `/v2/corporations/{corporation_id}/contacts/`, `/v2/characters/{character_id}/contacts/`, and `/v2/alliances/{alliance_id}/contacts/` which will return an array of `label_ids` instead of `label_id` so that it's not necessary for the developer to figure out the bitmasking going on in these endpoints.

Here is the swagger spec for `label_ids`:
```
                            label_ids:
                                type: array
                                maxItems: 63
                                items:
                                    type: integer
                                    format: int64
                                    description: >-
                                        Label IDs applied to the contact.
```
