### ISSUE TITLE
[SDE & ESI] concord agents still present

### ISSUE THREAD

**Issue by guiguilechat** [ccpgames/esi-issues#840]
Concord agents are removed from the in game agent finder, I assume they are removed from the game.

However they are still present in the SDE , and eg in dotlan.
http://evemaps.dotlan.net/agent/Aunou_Jareliellan

sde : bsd/agtAgents.yaml line 58417
```yaml
-   agentID: 3015737
    agentTypeID: 2
    corporationID: 1000125
    divisionID: 24
    isLocator: false
    level: 3
    locationID: 60012274
    quality: 20
```

ESI : https://esi.tech.ccp.is/latest/characters/3015737/
```
{
  "corporation_id": 1000125,
  "birthday": "2003-12-04T16:29:00Z",
  "name": "Aunou Jareliellan",
  "gender": "male",
  "race_id": 8,
  "bloodline_id": 8,
  "description": "",
  "ancestry_id": 17,
  "security_status": 0
}
```

**Comment by guiguilechat** [comment]
https://www.eveonline.com/article/jovian-and-concord-agents/

**Comment by ccp-pinky** [comment]
Although they are invisible in-game, doesn't mean they are removed ;) They are also still available in the client data files. So the assumption is not true.

Whether Game Design will ever actually remove them, or reuse them for other content: only time will tell. For now at least, this is not a bug, and the characters in question should be listed in the SDE.

**Comment by guiguilechat** [comment]
I understand that for things like items those can be present in the DB while not being usable directly.

However the agents are interactions available to the player. The agent is effectively not available in the game.

The corresponding lines in the new npcCharacters.yaml L201534 is
```yaml
3015737:
  agent:
    agentTypeID: 2
    divisionID: 24
    isLocator: false
    level: 3
  ancestryID: 17
  bloodlineID: 8
  careerID: 87
  ceo: false
  corporationID: 1000125
  gender: true
  locationID: 60012274
  name:
    de: Aunou Jareliellan
    en: Aunou Jareliellan
    es: Aunou Jareliellan
    fr: Aunou Jareliellan
    ja: アーニュー・ヤレリエラン
    ko: 아우누 자렐리엘란
    ru: Aunou Jareliellan
    zh: 阿努·贾日利安
  raceID: 8
  schoolID: 22
  specialityID: 87
  startDate: '2003-12-04 16:29:00'
  uniqueName: true
```

agent Type is (agentTypes.yaml L3)
```yaml
2:
  name: BasicAgent
```

division is (npcCorporationDivisions.yaml L64)
```yaml
24:
  displayName: New security division
  internalName: Security
  leaderTypeName:
    de: Kommandeur
    en: Commander
    es: Comandante
    fr: Commandant
    ja: 司令官
    ko: 사령관
    ru: Коман��ир
    zh: 指挥官
  name:
    de: Sicherheit
    en: Security
    es: Seguridad
    fr: Sécurité
    ja: セキュリティ
    ko: 보안
    ru: Служба безопасности
    zh: 安全
```

Is there way to deduce that this agent is not available for players in the game ?
